const electron = require('electron');
const dialog = electron.dialog;
const sqlite3 = require('sqlite3').verbose();
export const db = new sqlite3.Database('db.sqlite3');

export const setupDatabase = () => {
  db.serialize(()=>{
    insertTableHospital();
  });
  db.close();
  dialog.showMessageBox({type: 'info', title: 'Thông báo', message: 'Đã khởi tạo Database thành công, bạn có thể tiếp tục sử dụng ứng dụng.'});
}

function insertTableHospital() {
  db.run("DROP TABLE IF EXISTS hospital");
  db.run("CREATE TABLE hospital(code INTEGER PRIMARY KEY, name TEXT, province TEXT, channel TEXT)");
  db.run("INSERT INTO hospital(code, name, province, channel) VALUES(?, ?, ?, ?)", 1, 'Từ Dũ', 'Hồ Chí Minh', 'Key Urban');
  db.run("INSERT INTO hospital(code, name, province, channel) VALUES(?, ?, ?, ?)", 2, 'Hùng Vương', 'Hồ Chí Minh', 'Key Urban');
  db.run("INSERT INTO hospital(code, name, province, channel) VALUES(?, ?, ?, ?)", 3, 'PS Mê Kông', 'Hồ Chí Minh', 'Key Urban');
  db.run("INSERT INTO hospital(code, name, province, channel) VALUES(?, ?, ?, ?)", 4, 'BV Gia Định', 'Hồ Chí Minh', 'Key Urban');
  db.run("INSERT INTO hospital(code, name, province, channel) VALUES(?, ?, ?, ?)", 5, 'Nguyễn Tri Phương', 'Hồ Chí Minh', 'Key Urban');
  db.run("INSERT INTO hospital(code, name, province, channel) VALUES(?, ?, ?, ?)", 6, 'Quận Thủ Đức', 'Hồ Chí Minh', 'Key Urban');
  db.run("INSERT INTO hospital(code, name, province, channel) VALUES(?, ?, ?, ?)", 7, 'Đa Khoa Thủ Đức', 'Hồ Chí Minh', 'Key Urban');
  db.run("INSERT INTO hospital(code, name, province, channel) VALUES(?, ?, ?, ?)", 8, 'PS Trung Ương', 'Hà Nội', 'Key Urban');
  db.run("INSERT INTO hospital(code, name, province, channel) VALUES(?, ?, ?, ?)", 9, 'PS Hà Nội', 'Hà Nội', 'Key Urban');
  db.run("INSERT INTO hospital(code, name, province, channel) VALUES(?, ?, ?, ?)", 10, 'BV Bưu Điện Hà Nội', 'Hà Nội', 'Key Urban');
  db.run("INSERT INTO hospital(code, name, province, channel) VALUES(?, ?, ?, ?)", 11, 'Quân Y 103', 'Hà Nội', 'Key Urban');
  db.run("INSERT INTO hospital(code, name, province, channel) VALUES(?, ?, ?, ?)", 12, '108', 'Hà Nội', 'Key Urban');
  db.run("INSERT INTO hospital(code, name, province, channel) VALUES(?, ?, ?, ?)", 13, 'Bạch Mai', 'Hà Nội', 'Key Urban');
  db.run("INSERT INTO hospital(code, name, province, channel) VALUES(?, ?, ?, ?)", 14, 'Hà Đông', 'Hà Nội', 'Key Urban');
  db.run("INSERT INTO hospital(code, name, province, channel) VALUES(?, ?, ?, ?)", 15, 'Sản Nhi Đà Nẵng', 'Đà Nẵng', 'Key Urban');
  db.run("INSERT INTO hospital(code, name, province, channel) VALUES(?, ?, ?, ?)", 16, 'BV Quận Liên Chiểu', 'Đà Nẵng', 'Key Urban');
  db.run("INSERT INTO hospital(code, name, province, channel) VALUES(?, ?, ?, ?)", 17, 'TW Cần Thơ', 'Cần Thơ', 'Key Urban');
  db.run("INSERT INTO hospital(code, name, province, channel) VALUES(?, ?, ?, ?)", 18, 'TTCSSK SS Cần Thơ', 'Cần Thơ', 'Key Urban');
  db.run("INSERT INTO hospital(code, name, province, channel) VALUES(?, ?, ?, ?)", 19, 'BVĐK Cần Thơ', 'Cần Thơ', 'Key Urban');
  db.run("INSERT INTO hospital(code, name, province, channel) VALUES(?, ?, ?, ?)", 20, 'PS Cần Thơ', 'Cần Thơ', 'Key Urban');
  db.run("INSERT INTO hospital(code, name, province, channel) VALUES(?, ?, ?, ?)", 21, 'BV ĐK Khánh Hòa', 'Khánh Hòa', 'Key Urban');
  db.run("INSERT INTO hospital(code, name, province, channel) VALUES(?, ?, ?, ?)", 22, 'BV Phụ Sản Hải Phòng', 'Hải Phòng', 'Key Urban');
  db.run("INSERT INTO hospital(code, name, province, channel) VALUES(?, ?, ?, ?)", 23, 'BV Tâm Phúc Hải Phòng', 'Hải Phòng', 'Key Urban');
  db.run("INSERT INTO hospital(code, name, province, channel) VALUES(?, ?, ?, ?)", 24, 'ĐK TP Vinh', 'Nghệ An', 'Urban');
  db.run("INSERT INTO hospital(code, name, province, channel) VALUES(?, ?, ?, ?)", 25, 'BV Thái An', 'Nghệ An', 'Urban');
  db.run("INSERT INTO hospital(code, name, province, channel) VALUES(?, ?, ?, ?)", 26, 'BV 115', 'Nghệ An', 'Urban');
  db.run("INSERT INTO hospital(code, name, province, channel) VALUES(?, ?, ?, ?)", 27, 'BV Hữu Nghị Nghệ An', 'Nghệ An', 'Urban');
  db.run("INSERT INTO hospital(code, name, province, channel) VALUES(?, ?, ?, ?)", 28, 'Sản Nhi Nghệ An', 'Nghệ An', 'Urban');
  db.run("INSERT INTO hospital(code, name, province, channel) VALUES(?, ?, ?, ?)", 29, 'BV Bãi Cháy', 'Quảng Ninh', 'Urban');
  db.run("INSERT INTO hospital(code, name, province, channel) VALUES(?, ?, ?, ?)", 30, 'BV Sản Nhi Quảng Ninh', 'Quảng Ninh', 'Urban');
  db.run("INSERT INTO hospital(code, name, province, channel) VALUES(?, ?, ?, ?)", 31, 'BVĐK TW Thái Nguyên', 'Thái Nguyên', 'Urban');
  db.run("INSERT INTO hospital(code, name, province, channel) VALUES(?, ?, ?, ?)", 32, 'BV Gang Thép Thái Nguyên ', 'Thái Nguyên', 'Urban');
  db.run("INSERT INTO hospital(code, name, province, channel) VALUES(?, ?, ?, ?)", 33, 'BV Phụ Sản Thanh Hóa', 'Thanh Hóa', 'Urban');
  db.run("INSERT INTO hospital(code, name, province, channel) VALUES(?, ?, ?, ?)", 34, 'BV ĐK Thanh Hóa', 'Thanh Hóa', 'Urban');
  db.run("INSERT INTO hospital(code, name, province, channel) VALUES(?, ?, ?, ?)", 35, 'TTCSSK SS Thanh Hóa', 'Thanh Hóa', 'Urban');
  db.run("INSERT INTO hospital(code, name, province, channel) VALUES(?, ?, ?, ?)", 36, 'PS Hải Dương', 'Hải Dương', 'Urban');
  db.run("INSERT INTO hospital(code, name, province, channel) VALUES(?, ?, ?, ?)", 37, 'BVĐK Hải Dương', 'Hải Dương', 'Urban');
  db.run("INSERT INTO hospital(code, name, province, channel) VALUES(?, ?, ?, ?)", 38, 'Phòng Khám BV Y Học Cổ Truyền Hải Dương', 'Hải Dương', 'Urban');
  db.run("INSERT INTO hospital(code, name, province, channel) VALUES(?, ?, ?, ?)", 39, 'BVĐK Phú Thọ', 'Phú Thọ', 'Urban');
  db.run("INSERT INTO hospital(code, name, province, channel) VALUES(?, ?, ?, ?)", 40, 'TTCSSK SS Việt Trì', 'Phú Thọ', 'Urban');
  db.run("INSERT INTO hospital(code, name, province, channel) VALUES(?, ?, ?, ?)", 41, 'BV ĐK Thái Bình', 'Thái Bình', 'Urban');
  db.run("INSERT INTO hospital(code, name, province, channel) VALUES(?, ?, ?, ?)", 42, 'TTCSSK SS Thái Bình', 'Thái Bình', 'Urban');
  db.run("INSERT INTO hospital(code, name, province, channel) VALUES(?, ?, ?, ?)", 43, 'BV PS Nhi Thái Bình', 'Thái Bình', 'Urban');
  db.run("INSERT INTO hospital(code, name, province, channel) VALUES(?, ?, ?, ?)", 44, 'BV Phụ Sản Nam Định', 'Nam Định', 'Urban');
  db.run("INSERT INTO hospital(code, name, province, channel) VALUES(?, ?, ?, ?)", 45, 'BvĐK Nam Định', 'Nam Định', 'Urban');
  db.run("INSERT INTO hospital(code, name, province, channel) VALUES(?, ?, ?, ?)", 46, 'Sản Nhi Bắc Ninh', 'Bắc Ninh', 'Urban');
  db.run("INSERT INTO hospital(code, name, province, channel) VALUES(?, ?, ?, ?)", 47, 'BVĐK Từ Sơn', 'Bắc Ninh', 'Urban');
  db.run("INSERT INTO hospital(code, name, province, channel) VALUES(?, ?, ?, ?)", 48, 'BVĐK Tiên Du', 'Bắc Ninh', 'Urban');
  db.run("INSERT INTO hospital(code, name, province, channel) VALUES(?, ?, ?, ?)", 49, 'BVĐK Y Dược', 'Gia Lai', 'Urban');
  db.run("INSERT INTO hospital(code, name, province, channel) VALUES(?, ?, ?, ?)", 50, 'ĐK TW Huế', 'Huế', 'Urban');
  db.run("INSERT INTO hospital(code, name, province, channel) VALUES(?, ?, ?, ?)", 51, 'Y Dược Huế', 'Huế', 'Urban');
  db.run("INSERT INTO hospital(code, name, province, channel) VALUES(?, ?, ?, ?)", 52, 'BV Sản Nhi Quảng Ngãi', 'Quảng Ngãi', 'Urban');
  db.run("INSERT INTO hospital(code, name, province, channel) VALUES(?, ?, ?, ?)", 53, 'BVĐK Thiện Hạnh', 'Đăk Lăk', 'Urban');
  db.run("INSERT INTO hospital(code, name, province, channel) VALUES(?, ?, ?, ?)", 54, 'BVĐK Daklak', 'Đăk Lăk', 'Urban');
  db.run("INSERT INTO hospital(code, name, province, channel) VALUES(?, ?, ?, ?)", 55, 'ĐK Bình Định', 'Bình Định', 'Urban');
  db.run("INSERT INTO hospital(code, name, province, channel) VALUES(?, ?, ?, ?)", 56, 'DK KV Quảng Nam', 'Quảng Nam', 'Urban');
  db.run("INSERT INTO hospital(code, name, province, channel) VALUES(?, ?, ?, ?)", 57, 'TTCSSK SS Bình Dương', 'Bình Dương', 'Urban');
  db.run("INSERT INTO hospital(code, name, province, channel) VALUES(?, ?, ?, ?)", 58, 'Đa Khoa Đồng Nai', 'Đồng Nai', 'Urban');
  db.run("INSERT INTO hospital(code, name, province, channel) VALUES(?, ?, ?, ?)", 59, 'BV ĐK Bình Thuận', 'Bình Thuận', 'Urban');
  db.run("INSERT INTO hospital(code, name, province, channel) VALUES(?, ?, ?, ?)", 60, 'BVĐK Tây Ninh', 'Tây Ninh', 'Urban');
  db.run("INSERT INTO hospital(code, name, province, channel) VALUES(?, ?, ?, ?)", 61, 'BV Cao Văn Chí', 'Tây Ninh', 'Urban');
  db.run("INSERT INTO hospital(code, name, province, channel) VALUES(?, ?, ?, ?)", 62, 'BVĐK Lâm Đồng', 'Lâm Đồng', 'Urban');
  db.run("INSERT INTO hospital(code, name, province, channel) VALUES(?, ?, ?, ?)", 63, 'PS Tiền Giang', 'Tiền Giang', 'Urban');
  db.run("INSERT INTO hospital(code, name, province, channel) VALUES(?, ?, ?, ?)", 64, 'TTCSSK SS An Giang', 'An Giang', 'Urban');
  db.run("INSERT INTO hospital(code, name, province, channel) VALUES(?, ?, ?, ?)", 65, 'BV Sản Nhi An Giang', 'An Giang', 'Urban');
  db.run("INSERT INTO hospital(code, name, province, channel) VALUES(?, ?, ?, ?)", 66, 'BV ĐK Trung Tâm An Giang', 'An Giang', 'Urban');
  db.run("INSERT INTO hospital(code, name, province, channel) VALUES(?, ?, ?, ?)", 67, 'Sản Nhi Trà Vinh', 'Trà Vinh', 'Urban');
  db.run("INSERT INTO hospital(code, name, province, channel) VALUES(?, ?, ?, ?)", 68, 'ĐK Trà Vinh', 'Trà Vinh', 'Urban');
  db.run("INSERT INTO hospital(code, name, province, channel) VALUES(?, ?, ?, ?)", 69, 'BV ĐK Kiên giang', 'Kiên Giang', 'Urban');
  db.run("INSERT INTO hospital(code, name, province, channel) VALUES(?, ?, ?, ?)", 70, 'TTCSSK SS Kiên Giang', 'Kiên Giang', 'Urban');
  db.run("INSERT INTO hospital(code, name, province, channel) VALUES(?, ?, ?, ?)", 71, 'BV Sản Nhi Cà Mau', 'Cà Mau', 'Urban');
  db.run("INSERT INTO hospital(code, name, province, channel) VALUES(?, ?, ?, ?)", 72, 'BvĐK Đồng Tháp', 'Đồng Tháp', 'Urban');
  db.run("INSERT INTO hospital(code, name, province, channel) VALUES(?, ?, ?, ?)", 73, 'BVĐK Tỉnh Vĩnh Long', 'Vĩnh Long', 'Urban');
  db.run("INSERT INTO hospital(code, name, province, channel) VALUES(?, ?, ?, ?)", 74, 'BV TP Vĩnh Long', 'Vĩnh Long', 'Urban');
  db.run("INSERT INTO hospital(code, name, province, channel) VALUES(?, ?, ?, ?)", 75, 'BỆNH VIỆN SẢN NHI BẮC GIANG', 'Bắc Giang', 'Rural');
  db.run("INSERT INTO hospital(code, name, province, channel) VALUES(?, ?, ?, ?)", 76, 'PK BS THANH', 'Bắc Giang', 'Rural');
  db.run("INSERT INTO hospital(code, name, province, channel) VALUES(?, ?, ?, ?)", 77, 'BỆNH VIỆN HUYỆN THANH HÀ', 'Hải Dương', 'Rural');
  db.run("INSERT INTO hospital(code, name, province, channel) VALUES(?, ?, ?, ?)", 78, 'PK SAN HUYỆN THANH HÀ', 'Hải Dương', 'Rural');
  db.run("INSERT INTO hospital(code, name, province, channel) VALUES(?, ?, ?, ?)", 79, 'BỆNH ViỆN ĐK KIM THANH', 'Hải Dương', 'Rural');
  db.run("INSERT INTO hospital(code, name, province, channel) VALUES(?, ?, ?, ?)", 80, 'BỆNH VIỆN PHỤ SẢN HƯNG YÊN', 'Hưng Yên', 'Rural');
  db.run("INSERT INTO hospital(code, name, province, channel) VALUES(?, ?, ?, ?)", 81, 'PK SAN HƯNG YÊN', 'Hưng Yên', 'Rural');
  db.run("INSERT INTO hospital(code, name, province, channel) VALUES(?, ?, ?, ?)", 82, 'BỆNH VIỆN HUYỆN PHÚC YÊN', 'Vĩnh Phúc', 'Rural');
  db.run("INSERT INTO hospital(code, name, province, channel) VALUES(?, ?, ?, ?)", 83, 'BỆNH VIỆN HUYỆN VĨNH TƯỜNG', 'Vĩnh Phúc', 'Rural');
  db.run("INSERT INTO hospital(code, name, province, channel) VALUES(?, ?, ?, ?)", 84, 'BỆNH VIỆN ĐA KHOA TW THÁI NGUYÊN', 'Thái Nguyên', 'Rural');
  db.run("INSERT INTO hospital(code, name, province, channel) VALUES(?, ?, ?, ?)", 85, 'BỆNH VIỆN XUÂN TRƯỜNG', 'Nam Định', 'Rural');
  db.run("INSERT INTO hospital(code, name, province, channel) VALUES(?, ?, ?, ?)", 86, 'BỆNH VIỆN TRỰC NINH', 'Nam Định', 'Rural');
  db.run("INSERT INTO hospital(code, name, province, channel) VALUES(?, ?, ?, ?)", 87, 'PK SAN HUYỆN TRỰC NINH', 'Nam Định', 'Rural');
  db.run("INSERT INTO hospital(code, name, province, channel) VALUES(?, ?, ?, ?)", 88, 'BỆNH VIỆN THỊ XÃ SẦM SƠN', 'Thanh Hóa', 'Rural');
  db.run("INSERT INTO hospital(code, name, province, channel) VALUES(?, ?, ?, ?)", 89, 'BỆNH VIỆN TX BỈM SƠN', 'Thanh Hóa', 'Rural');
  db.run("INSERT INTO hospital(code, name, province, channel) VALUES(?, ?, ?, ?)", 90, 'BỆNH VIỆN HUYỆN BÁ THƯỚC', 'Thanh Hóa', 'Rural');
  db.run("INSERT INTO hospital(code, name, province, channel) VALUES(?, ?, ?, ?)", 91, 'PK SAN TX SẦM SƠN', 'Thanh Hóa', 'Rural');
  db.run("INSERT INTO hospital(code, name, province, channel) VALUES(?, ?, ?, ?)", 92, 'BỆNH VIỆN ĐA KHOA KỲ SƠN', 'Nghệ An', 'Rural');
  db.run("INSERT INTO hospital(code, name, province, channel) VALUES(?, ?, ?, ?)", 93, 'BỆNH VIỆN ĐA KHOA TƯƠNG DƯƠNG', 'Nghệ An', 'Rural');
  db.run("INSERT INTO hospital(code, name, province, channel) VALUES(?, ?, ?, ?)", 94, 'BỆNH VIỆN ĐA KHOA HUYỆN ANH SƠN', 'Nghệ An', 'Rural');
  db.run("INSERT INTO hospital(code, name, province, channel) VALUES(?, ?, ?, ?)", 95, 'BỆNH VIỆN ĐA KHOA TỈNH PHÚ THỌ', 'Phú Thọ', 'Rural');
  db.run("INSERT INTO hospital(code, name, province, channel) VALUES(?, ?, ?, ?)", 96, 'TRUNG TAM CSSK SINH SẢN', 'Phú Thọ', 'Rural');
  db.run("INSERT INTO hospital(code, name, province, channel) VALUES(?, ?, ?, ?)", 97, 'PK BS SẢN KHOA', 'Phú Thọ', 'Rural');
  db.run("INSERT INTO hospital(code, name, province, channel) VALUES(?, ?, ?, ?)", 98, 'PK SẢN KHOA 2', 'Phú Thọ', 'Rural');
  db.run("INSERT INTO hospital(code, name, province, channel) VALUES(?, ?, ?, ?)", 99, 'BỆNH VIỆN ĐK HUYỆN KIM ĐẬU', 'Hà Tĩnh', 'Rural');
  db.run("INSERT INTO hospital(code, name, province, channel) VALUES(?, ?, ?, ?)", 100, 'BỆNH VIỆN HUYỆN KIM NỮ', 'Hà Tĩnh', 'Rural');
  db.run("INSERT INTO hospital(code, name, province, channel) VALUES(?, ?, ?, ?)", 101, 'BỆNH VIỆN ÂN THI', 'Hà Tĩnh', 'Rural');
  db.run("INSERT INTO hospital(code, name, province, channel) VALUES(?, ?, ?, ?)", 102, 'BỆNH VIỆN HUYỆN QUỲNH PHỤ', 'Thái Bình', 'Rural');
  db.run("INSERT INTO hospital(code, name, province, channel) VALUES(?, ?, ?, ?)", 103, 'BỆNH VIỆN HUYỆN TIỀN HẢI', 'Thái Bình', 'Rural');
  db.run("INSERT INTO hospital(code, name, province, channel) VALUES(?, ?, ?, ?)", 104, 'PK SẢN HUYỆN QUỲNH PHỤ', 'Thái Bình', 'Rural');
  db.run("INSERT INTO hospital(code, name, province, channel) VALUES(?, ?, ?, ?)", 105, 'BỆNH VIỆN HUYỆN ĐIỆN BÀN', 'Quảng Nam', 'Rural');
  db.run("INSERT INTO hospital(code, name, province, channel) VALUES(?, ?, ?, ?)", 106, 'BỆNH VIỆN HUYỆN TIÊN PHƯỚC', 'Quảng Nam', 'Rural');
  db.run("INSERT INTO hospital(code, name, province, channel) VALUES(?, ?, ?, ?)", 107, 'BỆNH VIỆN NAM GIANG', 'Quảng Nam', 'Rural');
  db.run("INSERT INTO hospital(code, name, province, channel) VALUES(?, ?, ?, ?)", 108, 'BỆNH VIỆN HIỆP ĐỨC', 'Quảng Nam', 'Rural');
  db.run("INSERT INTO hospital(code, name, province, channel) VALUES(?, ?, ?, ?)", 109, 'BỆNH VIỆN HUYỆN CHƯ PĂN', 'Gia Lai', 'Rural');
  db.run("INSERT INTO hospital(code, name, province, channel) VALUES(?, ?, ?, ?)", 110, 'BỆNH VIỆN HUYỆN CHƯ PRONG', 'Gia Lai', 'Rural');
  db.run("INSERT INTO hospital(code, name, province, channel) VALUES(?, ?, ?, ?)", 111, 'BỆNH VIỆN HUYỆN ĐỨC CƠ', 'Gia Lai', 'Rural');
  db.run("INSERT INTO hospital(code, name, province, channel) VALUES(?, ?, ?, ?)", 112, 'BỆNH VIỆN HUYỆN CHƯ SÊ', 'Gia Lai', 'Rural');
  db.run("INSERT INTO hospital(code, name, province, channel) VALUES(?, ?, ?, ?)", 113, 'BỆNH ViỆN 331', 'Gia Lai', 'Rural');
  db.run("INSERT INTO hospital(code, name, province, channel) VALUES(?, ?, ?, ?)", 114, 'BỆNH VIỆN ĐK KV BỒNG SƠN', 'Bình Định', 'Rural');
  db.run("INSERT INTO hospital(code, name, province, channel) VALUES(?, ?, ?, ?)", 115, 'BỆNH VIỆN HOÀI ÂN', 'Bình Định', 'Rural');
  db.run("INSERT INTO hospital(code, name, province, channel) VALUES(?, ?, ?, ?)", 116, 'BỆNH VIỆN HUYỆN PHÙ MỸ', 'Bình Định', 'Rural');
  db.run("INSERT INTO hospital(code, name, province, channel) VALUES(?, ?, ?, ?)", 117, 'BỆNH VIỆN HUYỆN BUÔN ĐÔN', 'Đăk Lăk', 'Rural');
  db.run("INSERT INTO hospital(code, name, province, channel) VALUES(?, ?, ?, ?)", 118, 'BỆNH VIỆN KRONG BÔNG', 'Đăk Lăk', 'Rural');
  db.run("INSERT INTO hospital(code, name, province, channel) VALUES(?, ?, ?, ?)", 119, 'BỆNH VIỆN HUYỆN KRONG BUK', 'Đăk Lăk', 'Rural');
  db.run("INSERT INTO hospital(code, name, province, channel) VALUES(?, ?, ?, ?)", 120, 'BỆNH VIỆN HUYỆN EAHLEO', 'Đăk Lăk', 'Rural');
  db.run("INSERT INTO hospital(code, name, province, channel) VALUES(?, ?, ?, ?)", 121, 'BỆNH VIỆN HUYỆN BA SƠN', 'Quảng  Ngãi', 'Rural');
  db.run("INSERT INTO hospital(code, name, province, channel) VALUES(?, ?, ?, ?)", 122, 'PK SẢN HUYỆN ĐỨC PHỔ', 'Quảng  Ngãi', 'Rural');
  db.run("INSERT INTO hospital(code, name, province, channel) VALUES(?, ?, ?, ?)", 123, 'BỆNH VIỆN HUYỆN ĐỨC PHỔ', 'Quảng  Ngãi', 'Rural');
}
