const electron = require('electron');
const dialog = electron.dialog;
const sqlite3 = require('sqlite3').verbose();
export const db = new sqlite3.Database('db.sqlite3');

export const setupDatabase = () => {
  db.serialize(()=>{
    insertTableAreas();
    insertTableProvinces();
    insertTableHospitals();
  });
  db.close();
  dialog.showMessageBox({type: 'info', title: 'Thông báo', message: 'Đã khởi tạo Database thành công, bạn có thể tiếp tục sử dụng ứng dụng.'});
}

function insertTableAreas() {
  db.run("DROP TABLE IF EXISTS areas;");
  db.run("CREATE TABLE areas(area_id INTEGER PRIMARY KEY, name TEXT);");
  db.run("INSERT INTO areas(area_id, name) VALUES(?,?);", 1, 'Hồ Chí Minh');
  db.run('INSERT INTO areas(area_id, name) VALUES(?,?);', 2, 'Hà Nội');
  db.run('INSERT INTO areas(area_id, name) VALUES(?,?);', 3, 'Đà Nẵng');
  db.run('INSERT INTO areas(area_id, name) VALUES(?,?);', 4, 'Cần  Thơ');
  db.run('INSERT INTO areas(area_id, name) VALUES(?,?);', 5, 'Khánh Hòa');
  db.run('INSERT INTO areas(area_id, name) VALUES(?,?);', 6, 'Hải Phòng');
  db.run('INSERT INTO areas(area_id, name) VALUES(?,?);', 7, 'Miền Bắc - Urban');
  db.run('INSERT INTO areas(area_id, name) VALUES(?,?);', 8, 'Miền Trung - Urban');
  db.run('INSERT INTO areas(area_id, name) VALUES(?,?);', 10, 'Miền Tây - Urban');
  db.run('INSERT INTO areas(area_id, name) VALUES(?,?);', 9, 'Miền Đông - Urban');
  db.run('INSERT INTO areas(area_id, name) VALUES(?,?);', 11, 'Miền Bắc - Rural');
  db.run('INSERT INTO areas(area_id, name) VALUES(?,?);', 12, 'Miền Trung - Rural');
}

function insertTableProvinces() {
  db.run("DROP TABLE IF EXISTS provinces;");
  db.run("CREATE TABLE provinces(province_id INTEGER PRIMARY KEY, name TEXT, area_id INTEGER, FOREIGN KEY(area_id) REFERENCES areas(area_id));")
  db.run('INSERT INTO provinces(province_id, name, area_id) VALUES(?,?,?);', 1, 'Hồ Chí Minh', 1);
  db.run('INSERT INTO provinces(province_id, name, area_id) VALUES(?,?,?);', 2, 'Hà Nội', 2);
  db.run('INSERT INTO provinces(province_id, name, area_id) VALUES(?,?,?);', 3, 'Đà Nẵng', 3);
  db.run('INSERT INTO provinces(province_id, name, area_id) VALUES(?,?,?);', 4, 'Cần Thơ', 4);
  db.run('INSERT INTO provinces(province_id, name, area_id) VALUES(?,?,?);', 5, 'Khánh Hòa', 5);
  db.run('INSERT INTO provinces(province_id, name, area_id) VALUES(?,?,?);', 6, 'Hải Phòng', 6);
  db.run('INSERT INTO provinces(province_id, name, area_id) VALUES(?,?,?);', 7, 'Nghệ An - Urban', 7);
  db.run('INSERT INTO provinces(province_id, name, area_id) VALUES(?,?,?);', 8, 'Quảng Ninh', 7);
  db.run('INSERT INTO provinces(province_id, name, area_id) VALUES(?,?,?);', 9, 'Thái Nguyên - Urban', 7);
  db.run('INSERT INTO provinces(province_id, name, area_id) VALUES(?,?,?);', 10, 'Thanh Hóa - Urban', 7);
  db.run('INSERT INTO provinces(province_id, name, area_id) VALUES(?,?,?);', 11, 'Hải Dương - Urban', 7);
  db.run('INSERT INTO provinces(province_id, name, area_id) VALUES(?,?,?);', 12, 'Phú Thọ - Urban', 7);
  db.run('INSERT INTO provinces(province_id, name, area_id) VALUES(?,?,?);', 13, 'Thái Bình - Urban', 7);
  db.run('INSERT INTO provinces(province_id, name, area_id) VALUES(?,?,?);', 14, 'Hưng Yên - Urban', 7);
  db.run('INSERT INTO provinces(province_id, name, area_id) VALUES(?,?,?);', 15, 'Ninh Bình', 7);
  db.run('INSERT INTO provinces(province_id, name, area_id) VALUES(?,?,?);', 16, 'Vĩnh Phúc - Urban', 7);
  db.run('INSERT INTO provinces(province_id, name, area_id) VALUES(?,?,?);', 17, 'Bắc Ninh', 7);
  db.run('INSERT INTO provinces(province_id, name, area_id) VALUES(?,?,?);', 18, 'Huế ', 8);
  db.run('INSERT INTO provinces(province_id, name, area_id) VALUES(?,?,?);', 19, 'Quảng Ngãi - Urban', 8);
  db.run('INSERT INTO provinces(province_id, name, area_id) VALUES(?,?,?);', 20, 'Dak Lak - Urban', 8);
  db.run('INSERT INTO provinces(province_id, name, area_id) VALUES(?,?,?);', 21, 'Bình Định - Urban', 8);
  db.run('INSERT INTO provinces(province_id, name, area_id) VALUES(?,?,?);', 22, 'Quảng Nam - Urban', 8);
  db.run('INSERT INTO provinces(province_id, name, area_id) VALUES(?,?,?);', 23, 'Bình Dương', 9);
  db.run('INSERT INTO provinces(province_id, name, area_id) VALUES(?,?,?);', 24, 'Đồng Nai', 9);
  db.run('INSERT INTO provinces(province_id, name, area_id) VALUES(?,?,?);', 25, 'Bình Thuận', 9);
  db.run('INSERT INTO provinces(province_id, name, area_id) VALUES(?,?,?);', 26, 'Tiền Giang', 10);
  db.run('INSERT INTO provinces(province_id, name, area_id) VALUES(?,?,?);', 27, 'Bến Tre', 10);
  db.run('INSERT INTO provinces(province_id, name, area_id) VALUES(?,?,?);', 28, 'An Giang', 10);
  db.run('INSERT INTO provinces(province_id, name, area_id) VALUES(?,?,?);', 29, 'Trà Vinh', 10);
  db.run('INSERT INTO provinces(province_id, name, area_id) VALUES(?,?,?);', 30, 'Đồng Tháp', 10);
  db.run('INSERT INTO provinces(province_id, name, area_id) VALUES(?,?,?);', 31, 'Vĩnh Long', 10);
  db.run('INSERT INTO provinces(province_id, name, area_id) VALUES(?,?,?);', 32, 'Nghệ An - Rural', 11);
  db.run('INSERT INTO provinces(province_id, name, area_id) VALUES(?,?,?);', 33, 'Thái Nguyên -  Rural', 11);
  db.run('INSERT INTO provinces(province_id, name, area_id) VALUES(?,?,?);', 34, 'Thanh Hóa - Rural', 11);
  db.run('INSERT INTO provinces(province_id, name, area_id) VALUES(?,?,?);', 35, 'Hải Dương - Rural', 11);
  db.run('INSERT INTO provinces(province_id, name, area_id) VALUES(?,?,?);', 36, 'Phú Thọ - Rural', 11);
  db.run('INSERT INTO provinces(province_id, name, area_id) VALUES(?,?,?);', 37, 'Thái Bình - Rural', 11);
  db.run('INSERT INTO provinces(province_id, name, area_id) VALUES(?,?,?);', 38, 'Hưng Yên - Rural', 11);
  db.run('INSERT INTO provinces(province_id, name, area_id) VALUES(?,?,?);', 39, 'Vĩnh Phúc - Rural', 11);
  db.run('INSERT INTO provinces(province_id, name, area_id) VALUES(?,?,?);', 40, 'Bắc Giang', 11);
  db.run('INSERT INTO provinces(province_id, name, area_id) VALUES(?,?,?);', 41, 'Nam Định', 11);
  db.run('INSERT INTO provinces(province_id, name, area_id) VALUES(?,?,?);', 42, 'Quảng Ngãi - Rural', 12);
  db.run('INSERT INTO provinces(province_id, name, area_id) VALUES(?,?,?);', 43, 'Dak Lak - Rural', 12);
  db.run('INSERT INTO provinces(province_id, name, area_id) VALUES(?,?,?);', 44, 'Bình Định - Rural', 12);
  db.run('INSERT INTO provinces(province_id, name, area_id) VALUES(?,?,?);', 45, 'Quảng Nam - Rural', 12);
}

function insertTableHospitals() {
  db.run("DROP TABLE IF EXISTS hospitals;");
  db.run("CREATE TABLE hospitals(hospital_id INTEGER PRIMARY KEY, name TEXT, province_id INTEGER, area_id INTEGER, FOREIGN KEY(province_id) REFERENCES provinces(province_id), FOREIGN KEY(area_id) REFERENCES areas(area_id));");
  db.run('INSERT INTO hospitals(hospital_id, name, province_id, area_id) VALUES(?,?,?,?);', 1, 'Từ Dũ', 1, 1);
  db.run('INSERT INTO hospitals(hospital_id, name, province_id, area_id) VALUES(?,?,?,?);', 2, 'Hùng Vương', 1, 1);
  db.run('INSERT INTO hospitals(hospital_id, name, province_id, area_id) VALUES(?,?,?,?);', 3, 'Bv Phụ Sản MeKong', 1, 1);
  db.run('INSERT INTO hospitals(hospital_id, name, province_id, area_id) VALUES(?,?,?,?);', 4, 'Bv Quận Tân Phú', 1, 1);
  db.run('INSERT INTO hospitals(hospital_id, name, province_id, area_id) VALUES(?,?,?,?);', 5, 'Bv Quốc Ánh', 1, 1);
  db.run('INSERT INTO hospitals(hospital_id, name, province_id, area_id) VALUES(?,?,?,?);', 6, 'Bv Hóc Môn', 1, 1);
  db.run('INSERT INTO hospitals(hospital_id, name, province_id, area_id) VALUES(?,?,?,?);', 7, 'Nguyễn Tri Phương', 1, 1);
  db.run('INSERT INTO hospitals(hospital_id, name, province_id, area_id) VALUES(?,?,?,?);', 8, 'Quận Thủ Đức', 1, 1);
  db.run('INSERT INTO hospitals(hospital_id, name, province_id, area_id) VALUES(?,?,?,?);', 9, 'ĐK Thủ Đức', 1, 1);
  db.run('INSERT INTO hospitals(hospital_id, name, province_id, area_id) VALUES(?,?,?,?);', 10, 'PS Trung Ương', 2, 2);
  db.run('INSERT INTO hospitals(hospital_id, name, province_id, area_id) VALUES(?,?,?,?);', 11, 'PS Hà Nội', 2, 2);
  db.run('INSERT INTO hospitals(hospital_id, name, province_id, area_id) VALUES(?,?,?,?);', 12, 'Bv Bạch Mai', 2, 2);
  db.run('INSERT INTO hospitals(hospital_id, name, province_id, area_id) VALUES(?,?,?,?);', 13, 'Bv Bưu Điện', 2, 2);
  db.run('INSERT INTO hospitals(hospital_id, name, province_id, area_id) VALUES(?,?,?,?);', 14, 'Bv Nông Nghiệp', 2, 2);
  db.run('INSERT INTO hospitals(hospital_id, name, province_id, area_id) VALUES(?,?,?,?);', 15, '108', 2, 2);
  db.run('INSERT INTO hospitals(hospital_id, name, province_id, area_id) VALUES(?,?,?,?);', 16, 'Hà Đông', 2, 2);
  db.run('INSERT INTO hospitals(hospital_id, name, province_id, area_id) VALUES(?,?,?,?);', 17, 'Sản Nhi Đà Nẵng', 3, 3);
  db.run('INSERT INTO hospitals(hospital_id, name, province_id, area_id) VALUES(?,?,?,?);', 18, 'Bv Quận Sơn Trà', 3, 3);
  db.run('INSERT INTO hospitals(hospital_id, name, province_id, area_id) VALUES(?,?,?,?);', 19, 'Bv Quận Liên Chiểu', 3, 3);
  db.run('INSERT INTO hospitals(hospital_id, name, province_id, area_id) VALUES(?,?,?,?);', 20, 'TW Cần Thơ', 4, 4);
  db.run('INSERT INTO hospitals(hospital_id, name, province_id, area_id) VALUES(?,?,?,?);', 21, 'PS Cần Thơ', 4, 4);
  db.run('INSERT INTO hospitals(hospital_id, name, province_id, area_id) VALUES(?,?,?,?);', 22, 'Bv ĐK Khánh Hòa', 5, 5);
  db.run('INSERT INTO hospitals(hospital_id, name, province_id, area_id) VALUES(?,?,?,?);', 23, 'Bv Phụ Sản Hải Phòng', 6, 6);
  db.run('INSERT INTO hospitals(hospital_id, name, province_id, area_id) VALUES(?,?,?,?);', 24, 'ĐK TP Vinh', 7, 7);
  db.run('INSERT INTO hospitals(hospital_id, name, province_id, area_id) VALUES(?,?,?,?);', 25, 'Bv Thái An', 7, 7);
  db.run('INSERT INTO hospitals(hospital_id, name, province_id, area_id) VALUES(?,?,?,?);', 26, 'Bv 115', 7, 7);
  db.run('INSERT INTO hospitals(hospital_id, name, province_id, area_id) VALUES(?,?,?,?);', 27, 'Bv Hữu Nghị Nghệ An', 7, 7);
  db.run('INSERT INTO hospitals(hospital_id, name, province_id, area_id) VALUES(?,?,?,?);', 28, 'Sản Nhi Nghệ An', 7, 7);
  db.run('INSERT INTO hospitals(hospital_id, name, province_id, area_id) VALUES(?,?,?,?);', 29, 'Bv Bãi Cháy', 8, 7);
  db.run('INSERT INTO hospitals(hospital_id, name, province_id, area_id) VALUES(?,?,?,?);', 30, 'Bv Sản Nhi Quảng Ninh', 8, 7);
  db.run('INSERT INTO hospitals(hospital_id, name, province_id, area_id) VALUES(?,?,?,?);', 31, 'BvĐK TW Thái Nguyên', 9, 7);
  db.run('INSERT INTO hospitals(hospital_id, name, province_id, area_id) VALUES(?,?,?,?);', 32, 'Bv A Thái Nguyên', 9, 7);
  db.run('INSERT INTO hospitals(hospital_id, name, province_id, area_id) VALUES(?,?,?,?);', 33, 'Bv C Thái Nguyên', 9, 7);
  db.run('INSERT INTO hospitals(hospital_id, name, province_id, area_id) VALUES(?,?,?,?);', 34, 'Bv Gang Thép Thái Nguyên ', 9, 7);
  db.run('INSERT INTO hospitals(hospital_id, name, province_id, area_id) VALUES(?,?,?,?);', 35, 'Bv Phụ Sản Thanh Hóa', 10, 7);
  db.run('INSERT INTO hospitals(hospital_id, name, province_id, area_id) VALUES(?,?,?,?);', 36, 'Bv ĐK Thanh Hóa', 10, 7);
  db.run('INSERT INTO hospitals(hospital_id, name, province_id, area_id) VALUES(?,?,?,?);', 37, 'PS Hải Dương', 11, 7);
  db.run('INSERT INTO hospitals(hospital_id, name, province_id, area_id) VALUES(?,?,?,?);', 38, 'Bv Y Học Cổ Truyền Hải Dương', 11, 7);
  db.run('INSERT INTO hospitals(hospital_id, name, province_id, area_id) VALUES(?,?,?,?);', 39, 'Bv ĐK Phú Thọ', 12, 7);
  db.run('INSERT INTO hospitals(hospital_id, name, province_id, area_id) VALUES(?,?,?,?);', 40, 'Bv ĐK Thái Bình', 13, 7);
  db.run('INSERT INTO hospitals(hospital_id, name, province_id, area_id) VALUES(?,?,?,?);', 41, 'Bv PS Nhi Thái Bình', 13, 7);
  db.run('INSERT INTO hospitals(hospital_id, name, province_id, area_id) VALUES(?,?,?,?);', 42, 'Bv Hưng Hà', 14, 7);
  db.run('INSERT INTO hospitals(hospital_id, name, province_id, area_id) VALUES(?,?,?,?);', 43, 'Bv Sản Nhi Hưng Yên', 14, 7);
  db.run('INSERT INTO hospitals(hospital_id, name, province_id, area_id) VALUES(?,?,?,?);', 44, 'Bv Sản Nhi Ninh Bình', 15, 7);
  db.run('INSERT INTO hospitals(hospital_id, name, province_id, area_id) VALUES(?,?,?,?);', 45, 'Bv ĐK Vĩnh Phúc', 16, 7);
  db.run('INSERT INTO hospitals(hospital_id, name, province_id, area_id) VALUES(?,?,?,?);', 46, 'Bv Sản Nhi Vĩnh Phúc', 16, 7);
  db.run('INSERT INTO hospitals(hospital_id, name, province_id, area_id) VALUES(?,?,?,?);', 47, 'Sản Nhi Bắc Ninh', 17, 7);
  db.run('INSERT INTO hospitals(hospital_id, name, province_id, area_id) VALUES(?,?,?,?);', 48, 'Bv ĐK Từ Sơn', 17, 7);
  db.run('INSERT INTO hospitals(hospital_id, name, province_id, area_id) VALUES(?,?,?,?);', 49, 'Bv ĐK Tiên Du', 17, 7);
  db.run('INSERT INTO hospitals(hospital_id, name, province_id, area_id) VALUES(?,?,?,?);', 50, 'ĐK TW Huế', 18, 8);
  db.run('INSERT INTO hospitals(hospital_id, name, province_id, area_id) VALUES(?,?,?,?);', 51, 'Y Dược Huế', 18, 8);
  db.run('INSERT INTO hospitals(hospital_id, name, province_id, area_id) VALUES(?,?,?,?);', 52, 'Bv Dk Tp Quảng Ngãi', 19, 8);
  db.run('INSERT INTO hospitals(hospital_id, name, province_id, area_id) VALUES(?,?,?,?);', 53, 'Bv ĐK Thiện Hạnh', 20, 8);
  db.run('INSERT INTO hospitals(hospital_id, name, province_id, area_id) VALUES(?,?,?,?);', 54, 'Bv ĐK Daklak', 20, 8);
  db.run('INSERT INTO hospitals(hospital_id, name, province_id, area_id) VALUES(?,?,?,?);', 55, 'Bv ĐK Thị Xã Buôn hồ', 20, 8);
  db.run('INSERT INTO hospitals(hospital_id, name, province_id, area_id) VALUES(?,?,?,?);', 56, 'ĐK Bình Định', 21, 8);
  db.run('INSERT INTO hospitals(hospital_id, name, province_id, area_id) VALUES(?,?,?,?);', 57, 'ĐK KV Quảng Nam', 22, 8);
  db.run('INSERT INTO hospitals(hospital_id, name, province_id, area_id) VALUES(?,?,?,?);', 58, 'TTCSSK SS Bình Dương', 23, 9);
  db.run('INSERT INTO hospitals(hospital_id, name, province_id, area_id) VALUES(?,?,?,?);', 59, 'Bv Quân Đoàn 4', 23, 9);
  db.run('INSERT INTO hospitals(hospital_id, name, province_id, area_id) VALUES(?,?,?,?);', 60, 'Bv ĐK Bình Dương', 23, 9);
  db.run('INSERT INTO hospitals(hospital_id, name, province_id, area_id) VALUES(?,?,?,?);', 61, 'Đa Khoa Đồng Nai', 24, 9);
  db.run('INSERT INTO hospitals(hospital_id, name, province_id, area_id) VALUES(?,?,?,?);', 62, 'TTCSSK SS Bình Thuận', 25, 9);
  db.run('INSERT INTO hospitals(hospital_id, name, province_id, area_id) VALUES(?,?,?,?);', 63, 'Bv ĐK Bình Thuận', 25, 9);
  db.run('INSERT INTO hospitals(hospital_id, name, province_id, area_id) VALUES(?,?,?,?);', 64, 'PS Tiền Giang', 26, 10);
  db.run('INSERT INTO hospitals(hospital_id, name, province_id, area_id) VALUES(?,?,?,?);', 65, 'TTCSSK SS Tiền Giang', 26, 10);
  db.run('INSERT INTO hospitals(hospital_id, name, province_id, area_id) VALUES(?,?,?,?);', 66, 'Bv ĐK Nguyễn Đình Chiểu', 27, 10);
  db.run('INSERT INTO hospitals(hospital_id, name, province_id, area_id) VALUES(?,?,?,?);', 67, 'Bv Sản Nhi An Giang', 28, 10);
  db.run('INSERT INTO hospitals(hospital_id, name, province_id, area_id) VALUES(?,?,?,?);', 68, 'Bv ĐK Trung Tâm An Giang', 28, 10);
  db.run('INSERT INTO hospitals(hospital_id, name, province_id, area_id) VALUES(?,?,?,?);', 69, 'Sản Nhi Trà Vinh', 29, 10);
  db.run('INSERT INTO hospitals(hospital_id, name, province_id, area_id) VALUES(?,?,?,?);', 70, 'Bv ĐK Đồng Tháp', 30, 10);
  db.run('INSERT INTO hospitals(hospital_id, name, province_id, area_id) VALUES(?,?,?,?);', 71, 'Bv ĐK Tỉnh Vĩnh Long', 31, 10);
  db.run('INSERT INTO hospitals(hospital_id, name, province_id, area_id) VALUES(?,?,?,?);', 72, 'Bv TP Vĩnh Long', 31, 10);
  db.run('INSERT INTO hospitals(hospital_id, name, province_id, area_id) VALUES(?,?,?,?);', 73, 'Bv Huyện Cửa Lò', 32, 11);
  db.run('INSERT INTO hospitals(hospital_id, name, province_id, area_id) VALUES(?,?,?,?);', 74, 'Bv Huyện Diễn Châu', 32, 11);
  db.run('INSERT INTO hospitals(hospital_id, name, province_id, area_id) VALUES(?,?,?,?);', 75, 'Bv Huyện Hưng Nguyên', 32, 11);
  db.run('INSERT INTO hospitals(hospital_id, name, province_id, area_id) VALUES(?,?,?,?);', 76, 'Bv Huyện Nghi Lộc', 32, 11);
  db.run('INSERT INTO hospitals(hospital_id, name, province_id, area_id) VALUES(?,?,?,?);', 77, 'Bv Huyện Nam Đàn', 32, 11);
  db.run('INSERT INTO hospitals(hospital_id, name, province_id, area_id) VALUES(?,?,?,?);', 78, 'Bv Huyện Đồng Hỷ', 33, 11);
  db.run('INSERT INTO hospitals(hospital_id, name, province_id, area_id) VALUES(?,?,?,?);', 79, 'Bv Huyện Sông Công', 33, 11);
  db.run('INSERT INTO hospitals(hospital_id, name, province_id, area_id) VALUES(?,?,?,?);', 80, 'Bv Huyện Phú Lương', 33, 11);
  db.run('INSERT INTO hospitals(hospital_id, name, province_id, area_id) VALUES(?,?,?,?);', 81, 'Bv Huyện Lang chánh', 34, 11);
  db.run('INSERT INTO hospitals(hospital_id, name, province_id, area_id) VALUES(?,?,?,?);', 82, 'Bv Huyện Cẩm Thủy', 34, 11);
  db.run('INSERT INTO hospitals(hospital_id, name, province_id, area_id) VALUES(?,?,?,?);', 83, 'Bv Huyện Ngọc Lặc', 34, 11);
  db.run('INSERT INTO hospitals(hospital_id, name, province_id, area_id) VALUES(?,?,?,?);', 84, 'Bv Huyện Bá Thước', 34, 11);
  db.run('INSERT INTO hospitals(hospital_id, name, province_id, area_id) VALUES(?,?,?,?);', 85, 'Bv Huyện Thường Xuân', 34, 11);
  db.run('INSERT INTO hospitals(hospital_id, name, province_id, area_id) VALUES(?,?,?,?);', 86, 'Bv Huyện Cẩm Giàng', 35, 11);
  db.run('INSERT INTO hospitals(hospital_id, name, province_id, area_id) VALUES(?,?,?,?);', 87, 'Bv Huyện Gia Lộc', 35, 11);
  db.run('INSERT INTO hospitals(hospital_id, name, province_id, area_id) VALUES(?,?,?,?);', 88, 'Bv Huyện Nam Sách', 35, 11);
  db.run('INSERT INTO hospitals(hospital_id, name, province_id, area_id) VALUES(?,?,?,?);', 89, 'Bv Huyện Bình Giang', 35, 11);
  db.run('INSERT INTO hospitals(hospital_id, name, province_id, area_id) VALUES(?,?,?,?);', 90, 'Bv Huyện Thanh Hà', 35, 11);
  db.run('INSERT INTO hospitals(hospital_id, name, province_id, area_id) VALUES(?,?,?,?);', 91, 'Bv Huyện Lâm Thao', 36, 11);
  db.run('INSERT INTO hospitals(hospital_id, name, province_id, area_id) VALUES(?,?,?,?);', 92, 'Bv Huyện Song Thao', 36, 11);
  db.run('INSERT INTO hospitals(hospital_id, name, province_id, area_id) VALUES(?,?,?,?);', 93, 'Bv Huyện Tân Sơn', 36, 11);
  db.run('INSERT INTO hospitals(hospital_id, name, province_id, area_id) VALUES(?,?,?,?);', 94, 'Bv Huyện Vũ Thư', 37, 11);
  db.run('INSERT INTO hospitals(hospital_id, name, province_id, area_id) VALUES(?,?,?,?);', 95, 'Bv Huyện Đông Hưng', 37, 11);
  db.run('INSERT INTO hospitals(hospital_id, name, province_id, area_id) VALUES(?,?,?,?);', 96, 'Bv Huyện Tiền Hải', 37, 11);
  db.run('INSERT INTO hospitals(hospital_id, name, province_id, area_id) VALUES(?,?,?,?);', 97, 'Bv Huyện Kiến Xương', 37, 11);
  db.run('INSERT INTO hospitals(hospital_id, name, province_id, area_id) VALUES(?,?,?,?);', 98, 'Bv Huyện Phù Cừ', 38, 11);
  db.run('INSERT INTO hospitals(hospital_id, name, province_id, area_id) VALUES(?,?,?,?);', 99, 'Bv Huyện Kim Động', 38, 11);
  db.run('INSERT INTO hospitals(hospital_id, name, province_id, area_id) VALUES(?,?,?,?);', 100, 'Bv Huyện Ân Thi', 38, 11);
  db.run('INSERT INTO hospitals(hospital_id, name, province_id, area_id) VALUES(?,?,?,?);', 101, 'Bv Huyện Bình Sơn', 39, 11);
  db.run('INSERT INTO hospitals(hospital_id, name, province_id, area_id) VALUES(?,?,?,?);', 102, 'Bv Huyện Phúc Yên', 39, 11);
  db.run('INSERT INTO hospitals(hospital_id, name, province_id, area_id) VALUES(?,?,?,?);', 103, 'Bv Huyện Yên lạc', 39, 11);
  db.run('INSERT INTO hospitals(hospital_id, name, province_id, area_id) VALUES(?,?,?,?);', 104, 'Bv Huyện Lạng giang', 40, 11);
  db.run('INSERT INTO hospitals(hospital_id, name, province_id, area_id) VALUES(?,?,?,?);', 105, 'Bv Huyện Yên Dũng', 40, 11);
  db.run('INSERT INTO hospitals(hospital_id, name, province_id, area_id) VALUES(?,?,?,?);', 106, 'Bv Huyện Lục Nam', 40, 11);
  db.run('INSERT INTO hospitals(hospital_id, name, province_id, area_id) VALUES(?,?,?,?);', 107, 'Bv Huyện Tân yên', 40, 11);
  db.run('INSERT INTO hospitals(hospital_id, name, province_id, area_id) VALUES(?,?,?,?);', 108, 'Bv Huyện Mỹ Lộc', 41, 11);
  db.run('INSERT INTO hospitals(hospital_id, name, province_id, area_id) VALUES(?,?,?,?);', 109, 'Bv Huyện Nam Trực', 41, 11);
  db.run('INSERT INTO hospitals(hospital_id, name, province_id, area_id) VALUES(?,?,?,?);', 110, 'Bv Huyện Trực Ninh', 41, 11);
  db.run('INSERT INTO hospitals(hospital_id, name, province_id, area_id) VALUES(?,?,?,?);', 111, 'Bv Huyện Vụ Bản', 41, 11);
  db.run('INSERT INTO hospitals(hospital_id, name, province_id, area_id) VALUES(?,?,?,?);', 112, 'Bv Sơn Hà', 42, 12);
  db.run('INSERT INTO hospitals(hospital_id, name, province_id, area_id) VALUES(?,?,?,?);', 113, 'Bv Tư Nghĩa', 42, 12);
  db.run('INSERT INTO hospitals(hospital_id, name, province_id, area_id) VALUES(?,?,?,?);', 114, 'Bv Sơn Tịnh', 42, 12);
  db.run('INSERT INTO hospitals(hospital_id, name, province_id, area_id) VALUES(?,?,?,?);', 115, 'Bv Huyện Cư kuin', 43, 12);
  db.run('INSERT INTO hospitals(hospital_id, name, province_id, area_id) VALUES(?,?,?,?);', 116, 'Bv ĐK Huyện Krong pak', 43, 12);
  db.run('INSERT INTO hospitals(hospital_id, name, province_id, area_id) VALUES(?,?,?,?);', 117, 'Bv ĐK Cư M\'gar', 43, 12);
  db.run('INSERT INTO hospitals(hospital_id, name, province_id, area_id) VALUES(?,?,?,?);', 118, 'Bv ĐK Thị Xã Buôn hồ', 43, 12);
  db.run('INSERT INTO hospitals(hospital_id, name, province_id, area_id) VALUES(?,?,?,?);', 119, 'TT Y Tế Huyện An Nhơn', 44, 12);
  db.run('INSERT INTO hospitals(hospital_id, name, province_id, area_id) VALUES(?,?,?,?);', 120, 'Bv Huyện Tuy Phước', 44, 12);
  db.run('INSERT INTO hospitals(hospital_id, name, province_id, area_id) VALUES(?,?,?,?);', 121, 'Bv Huyện Phù Cát', 44, 12);
  db.run('INSERT INTO hospitals(hospital_id, name, province_id, area_id) VALUES(?,?,?,?);', 122, 'Bv DK TW Quảng Nam', 45, 12);
  db.run('INSERT INTO hospitals(hospital_id, name, province_id, area_id) VALUES(?,?,?,?);', 123, 'TT Y Tế Huyện Thăng Bình', 45, 12);
  db.run('INSERT INTO hospitals(hospital_id, name, province_id, area_id) VALUES(?,?,?,?);', 124, 'Bv Huyện Tiên Phước', 45, 12);
  db.run('INSERT INTO hospitals(hospital_id, name, province_id, area_id) VALUES(?,?,?,?);', 125, 'TT Y Tế Huyện Hiệp Đức', 45, 12);
}
